# Render deployment configuration for N8N
# This will deploy N8N alongside ZooCrewOS for G's integration

services:
  - type: web
    name: n8n
    env: image
    image: "n8nio/n8n"
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: yourusername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
